name: Sugerir uma melhoria
description: Uma ideia de recurso ou mudança.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema isso resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: Como você imagina que funcione.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
