// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as app$0 from "../../../../gustavofreitas/prompt-improve/internal/app/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "improve:chunk": app$0.ChunkEvent;
            "improve:done": app$0.DoneEvent;
            "improve:error": app$0.ErrorEvent;
            "selection:new": app$0.SelectionEvent;
            "state:changed": app$0.State;
        }
    }
}
