// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImproveService is bound to the frontend. Every exported method is a
 * binding, so non-frontend operations live on Host.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops the request with the given id; no further events are
 * emitted for it. Unknown or finished ids are ignored.
 */
export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(1301769902, id);
}

/**
 * Close cancels any in-flight request, hides the window and gives focus
 * back to the previously active app.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1672743312);
}

/**
 * Copy puts text in the clipboard.
 */
export function Copy(text: string): $CancellablePromise<void> {
    return $Call.ByID(1123328113, text);
}

/**
 * GetState returns the current modal state.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(1833121917);
}

/**
 * Replace pastes text into the source app (hides the window, returns focus,
 * then pastes and restores the clipboard). Fails when automatic paste is not
 * available in this session.
 */
export function Replace(text: string): $CancellablePromise<void> {
    return $Call.ByID(1682521732, text);
}

/**
 * Start runs an improvement in the background and returns its request id.
 * Any in-flight request is cancelled first. Results arrive as
 * improve:chunk / improve:done / improve:error events carrying this id.
 */
export function Start(req: $models.StartRequest): $CancellablePromise<string> {
    return $Call.ByID(1166551936, req);
}
