// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImproveService is bound to the frontend. Every exported method is a
 * binding, so non-frontend operations live on Host.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops the request with the given id; no further events are
 * emitted for it. Unknown or finished ids are ignored.
 */
export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(1301769902, id);
}

/**
 * Close cancels any in-flight request, hides the window and gives focus
 * back to the previously active app.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1672743312);
}

/**
 * CloseProfile hides the profile window.
 */
export function CloseProfile(): $CancellablePromise<void> {
    return $Call.ByID(3865186613);
}

/**
 * Copy puts text in the clipboard.
 */
export function Copy(text: string): $CancellablePromise<void> {
    return $Call.ByID(1123328113, text);
}

/**
 * GetProfile returns the profile of the current configuration.
 */
export function GetProfile(): $CancellablePromise<$models.ProfileDTO> {
    return $Call.ByID(3475515869);
}

/**
 * GetState returns the current modal state.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(1833121917);
}

/**
 * ListModels returns the models offered by the provider (for Ollama, the
 * installed ones), sorted. Errors are PT-BR and user-facing.
 */
export function ListModels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1437161750);
}

/**
 * Replace pastes text into the source app (hides the window, returns focus,
 * then pastes and restores the clipboard). Fails when automatic paste is not
 * available in this session. When the paste itself fails, the window is
 * shown again and text is left on the clipboard for a manual paste.
 */
export function Replace(text: string): $CancellablePromise<void> {
    return $Call.ByID(1682521732, text);
}

/**
 * SaveProfile validates p (enabled requires text; at most maxProfileChars
 * after trimming; CRLF becomes LF), persists it and reloads the
 * configuration. Errors are PT-BR and user-facing.
 */
export function SaveProfile(p: $models.ProfileDTO): $CancellablePromise<void> {
    return $Call.ByID(1063210010, p);
}

/**
 * SetModel persists model as provider.model and reloads the configuration;
 * the new model arrives on state:changed. Requests already running keep
 * the previous model.
 */
export function SetModel(model: string): $CancellablePromise<void> {
    return $Call.ByID(1639218321, model);
}

/**
 * Start runs an improvement in the background and returns its request id.
 * Any in-flight request is cancelled first. Results arrive as
 * improve:chunk / improve:done / improve:error events carrying this id.
 */
export function Start(req: $models.StartRequest): $CancellablePromise<string> {
    return $Call.ByID(1166551936, req);
}
