// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionDTO is an action as exposed to the frontend (no instruction).
 */
export interface ActionDTO {
    "id": string;
    "category": string;
    "label": string;
}

/**
 * ChunkEvent is the payload of improve:chunk.
 */
export interface ChunkEvent {
    "id": string;
    "delta": string;
}

/**
 * DoneEvent is the payload of improve:done; Text is improver.Clean(total).
 */
export interface DoneEvent {
    "id": string;
    "text": string;
}

/**
 * ErrorEvent is the payload of improve:error; Message is PT-BR.
 */
export interface ErrorEvent {
    "id": string;
    "message": string;
}

/**
 * ProfileDTO is the user profile as exposed to the frontend.
 */
export interface ProfileDTO {
    "enabled": boolean;
    "text": string;
}

/**
 * SelectionEvent is the payload of selection:new.
 */
export interface SelectionEvent {
    "text": string;
    "canReplace": boolean;
    "warning": string;
}

/**
 * StartRequest is the input of Start.
 */
export interface StartRequest {
    "text": string;
    "actionId": string;
    "freeInstruction": string;
}

/**
 * State is the modal state returned by GetState and sent on state:changed.
 */
export interface State {
    "text": string;
    "actions": ActionDTO[] | null;
    "canReplace": boolean;
    "warning": string;
    "error": string;
    "model": string;
}
